### ISSUE TITLE
[bug fix]If you use jei to mark fluid/gas/mana/energy in the export card screen, the wrong item will be exported

### ISSUE THREAD

**Issue by zhcn000000** [starforcraft/AE2-Import-Export-Card#11]
If possible, take the approach of adding functionality rather than disabling it to fix the problem,Adds the function to automatically export fluid/gas/mana/energy to handheld containers and automatically import them from handheld containers

**Comment by starforcraft** [comment]
Use EMI or ask here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/
