### ISSUE TITLE
Cards not functioning?

### ISSUE THREAD

**Issue by WhitePhant0m** [starforcraft/AE2-Import-Export-Card#12]
https://github.com/user-attachments/assets/69bc236f-cff2-4120-84f5-a9f188d3c31b

Cards don't seem to export/import any items?

MC: 1.21
Neo:  21.0.111-beta
Mod versions:
AE2 - 19.0.13-alpha
AE2WTLib 19.0.10-beta (Using the universal wterminal)
Import Export card 1.3.0

**Comment by starforcraft** [comment]
Can you try this with the newest import export card version (1.3.1)?

**Comment by WhitePhant0m** [comment]
Same results

**Comment by starforcraft** [comment]
Hmm then can you try the upgrade in a normal Wireless Terminal?

**Comment by WhitePhant0m** [comment]
After more testing, I figured out the cause.
I didn't link my wireless terminal by using Wireless Access point, but instead by using AE2WTLibs Quantum Bridge card.

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/ae2-import-export-card/files/5577253
