### ISSUE TITLE
[Suggestion] Mass select buttons in the UI and hybrid card

### ISSUE THREAD

**Issue by vizthex123** [starforcraft/AE2-Import-Export-Card#7]
Having a button that enables all inventory slots, everything but the hotbar, and just the hotbar (at least in the insert card's UI).

In addition, a single card that had the functionality of both cards would be great (and if you ever add more, there could be a super-combo card).

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/ae2-import-export-card/files/5551385

**Comment by starforcraft** [comment]
I don't like the idea of a hybrid card, so it won't be added, sorry
